### ISSUE TITLE
CSS not compiled

### ISSUE THREAD

**Issue by joekrie** [brunch/react-skeleton#12]
When I clone this project and run `brunch build`, the CSS file does not get put in the public folder. When I compared this repo to with-es6, the only difference I could find was that with-es6 has brunch under devDependencies. When I add brunch as a dev dependency to this project, the CSS does get placed in public.

**Comment by shvaikalesh** [comment]
Hey @joekrie, thanks for the issue. That happens because

1. global Brunch is used and it is not `2.10`
1. `css-brunch` is missing and only Brunch `>= 2.10` compiles CSS without it

Either way, we recommend having Brunch in `devDependencies`.
