### ISSUE TITLE
Material UI no longer works

### ISSUE THREAD

**Issue by adrianmcli** [brunch/react-skeleton#2]
This is strange because I used this same exact repo several weeks ago and everything worked fine.

This is the error I get in my console:

```
Uncaught Error: Cannot find module "react/lib/update" from "react-addons-update"
```

^ the above error was thrown inside `vendor.js`

This is my import statement that causes the app to crash:

``` js
import RaisedButton from 'material-ui/lib/raised-button';
```

All I did was initialize the skeleton with Brunch, and then `npm install --save material-ui`. This same exact methodology is how I started this repo: https://github.com/adrianmc/olis-frontend

An example of the non-working version is here: https://github.com/adrianmc/brunch-mui-example

I believe the culprit is inside how Brunch tries to fetch the dependencies when compiling `vendor.js`. That seems to be the only difference between the structure of the old repo as compared to the new repo.

**Comment by goshacmd** [comment]
Can you provide more details? Brunch version, your config, etc. Also the
actual errors you are getting.

Additionally, creating a small app on GitHub that demonstrates the issue
would be of great help.

**Comment by adrianmcli** [comment]
@goshakkk yeah I hit enter by accident, please wait while I edit it. My apologies.

**Comment by adrianmcli** [comment]
@goshakkk I've got an example repo up now. Feel free to clone it and see for yourself:

```
git clone https://github.com/adrianmc/brunch-mui-example
```

don't forget to run `npm install` first, and then launch it using `brunch watch --server`.

You'll notice that by removing the import line, everything seems to work fine.

I am currently using the latest Brunch 2.4.2

**Comment by goshacmd** [comment]
Yep, could reproduce.

However, brunch from master on gh is handling it correctly. Until we cut a release, do you mind running master brunch?

**Comment by paulmillr** [comment]
Brunch 2.5 is out. Try it now
