### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by ronnieoverby** [brunch/react-skeleton#3]
Brand new project is broken with browser console error:

> Uncaught Error: Cannot find module 'react/lib/ReactDOM' from 'react-dom/index.js'

**Comment by goshacmd** [comment]
Ooops, looks like an issue introduced by deppack 0.2.1... thanks for reporting! I'll be on it

**Comment by goshacmd** [comment]
https://github.com/brunch/brunch/pull/1254 should fix it. Thanks again!

**Comment by ronnieoverby** [comment]
NP
