### ISSUE TITLE
How to tests components ?

### ISSUE THREAD

**Issue by iamvdo** [brunch/react-skeleton#5]
I'm not sure where to post my issue, but I'm using this skeleton, so...
I have React components inside `app/components` and want to test them inside `test` folder.
Using mocha, I have my script test: `mocha --compilers js:babel-core/register test/*.test.jsx`, but it doesn't work (jsx inside) because babel config from `brunch-config.js` is not used. If I add a `.babelrc` file with same presets than `brunch-config.js`'s one, it works.

Is it expected behaviour or am I missing something ?
Thanks

**Comment by shvaikalesh** [comment]
**Short answer: yes**, it is expected.

Babel can not know all the ways configs may be specified: brunch, broccoli, gobble, fly etc. It looks only for `package.json` with `babel` field and `.babelrc`s and merges them together, unless `options.babelrc === false`.

It is not necessary to repeat Babel config twice &mdash; in `.babelrc` and `brunch-config.js`. `rc` should be recognized by `babel-brunch` just fine. Personally, I have quite a few custom transforms in Babel config and prefer to keep it in separate file.

By default, Babel 6 has no transforms. However, `babel-brunch` [adds `es2015` preset if none present](https://github.com/babel/babel-brunch/blob/master/index.js#L21), but yeah, not `jsx`. So make sure you specify `es201[56]` preset in `rc`.

If you would like to know more about Babel's options resolution, please check out [`OptionsManager`](https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/options/option-manager.js) class.

**Comment by ryansobol** [comment]
@shvaikalesh Correct me if I'm wrong, but the `babel-brunch` plugin doesn't recognize the `.babelrc` file. See babel/babel-brunch#41.

**Comment by rafaelkallis** [comment]
@shvaikalesh it seems `babel-brunch` does recognise the `.babelrc` now.

Add this in your `brunch-config.js`:

```
plugins: {
    babel: {
        babelrc: true
    }
}
```

**Comment by denysdovhan** [comment]
@ryansobol no, `babel-brunch` recognize `.babelrc` file just fine. The resolution is done by Babel itself.

Here I created the demo that uses `.babelrc`: https://github.com/denysdovhan/babelrc-brunch-demo.

There's a `transform-object-rest-spread` plugin defined in [`.babelrc`](https://github.com/denysdovhan/babelrc-brunch-demo/blob/master/.babelrc#L1-L4) and it's compile `app` folder without any problem.
